### ISSUE TITLE
[question] board processing issue on jlcpcb site

### ISSUE THREAD

**Issue by fizarum** [retro-esp32/RetroESP32-Design-Files#1]
**Is your feature request related to a problem? Please describe.**
First of all: I think its not a problem of board design but limitation of mentioned pcb service and I'm trying to solve it, any advices are welcome :)

There is an issue with processing gerber files (top side) on [JLCPCB](https://jlcpcb.com/) - the top silck screen overlaps top solder mask:
![new_design_jlcpcb](https://user-images.githubusercontent.com/4805242/85226617-b3daf300-b3d8-11ea-99ce-6a84ea92cef0.PNG)
 Looks like its a limitation of this service and final board may be produced with issues. For example 
[OSHPARK](oshpark.com) doesnt have this issue:
![new_design_oshpark](https://user-images.githubusercontent.com/4805242/85226353-68741500-b3d7-11ea-8eab-d831b69b41da.png)
but more expensive ($64.30 on OSHPARK and $6.40 on JLCPCB)

**Describe the solution you'd like**
I know there are some older designs which have another silck screen, for example [here](https://github.com/airainchoc/RetroESP32/tree/Hardware) I've found:
![old_design](https://user-images.githubusercontent.com/4805242/85226999-ade61180-b3da-11ea-88ba-a9dcc99dfda2.PNG)
So is it possible to add gerber files with older design as _compatible-with-cheap-pcb-service-solution_?

**Describe alternatives you've considered**
Or, if its possible, put some list of trusted (tested?) pcb services to make this board without such issues

**Comment by 32teeth** [comment]
### Hi there
Thanks for getting in touch

i am not familiar with JLCPCB, seems that this may be  an issue with the gerber viewer.\
take a [look here](https://gerber-viewer.easyeda.com/showcase/#!id=c7c9d71db47811ea947a026a86b9cae7&type=top&layer_list=1-2-3-4-5-6). this is a generic gerber viewer that most pcb shops use

here is an example of the output
![top](https://gerber-viewer.easyeda.com/api/png/c7c9d71db47811ea947a026a86b9cae7/?bgcolor=%230B3B0B&layers=drill-01%2Cdrill-02%2Csolder-mask-top%2Csilkscreen-top%2Ccopper-top%2Coutline&colors=%23000000%2C%23000000%2C%23DCAA14%2C%23FFFFFF%2C%2300BE00%2C%23FFFFFF&&realcopper)

below is a list of pcb houses previously used

- All PCB
- PCB Mart
- Seeed Studio

When you do order, ensure you select

- 1mm thickness
- gold enig (best solution for silicon buttons)

-----

> ## Although we do this for 💕 of 🕹️
> **We Also Like Coffee!**
> *Please Consider Supporting*<br>
> [![Support](https://raw.githubusercontent.com/retro-esp32/RetroESP32/master/Assets/sponsor.jpg)](https://github.com/sponsors/retro-esp32)

-----
