### ISSUE TITLE
You can update the ili9342c 45pin design file？

### ISSUE THREAD

**Issue by jianjinliao** [retro-esp32/RetroESP32-Design-Files#2]
Hi，Last time I discussed the screen of ili9342 with you. You said that the 9342c design file was updated. I am looking forward to building it。

**Comment by 32teeth** [comment]
hi @jianjinliao 
please understand this is a hobby
i am working on it and there are a few more things to test

if you would like to accelerate the process
i strongly recommend sponsorship or endorsement

[Endorse 32teeth](https://github.com/sponsors/32teeth)
[Endorse Retro ESP32](https://github.com/sponsors/retro-esp32)
